theme: jekyll-theme-minimal
title: MircoKato
description: Un dedalo di giochi di ruolo.

show_downloads: false #rimuove tasti per download codice
is_project_page: false #rimuove link al repository Github
